import { addDays, today } from './dates';
import { defaultSettings, type DeckData, type Task } from '../types';
export function makeTask(title: string, patch: Partial<Task> = {}): Task {
  return {
    id: crypto.randomUUID(),
    title,
    notes: '',
    stackId: null,
    heading: '',
    tags: [],
    scheduled: null,
    deadline: null,
    time: null,
    destination: 'anytime',
    priority: 0,
    recurrence: null,
    completedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    checklist: [],
    links: [],
    blockedBy: [],
    parentId: null,
    effort: 25,
    order: Date.now(),
    ...patch,
  };
}
export function seedData(): DeckData {
  const tasks = [
    makeTask('Deploy Repo Reaper', {
      id: 'deploy',
      stackId: 'oddware',
      scheduled: today(),
      priority: 2,
      deadline: today(),
      tags: ['shipping'],
      notes:
        'A small launch, a big step forward.\n\n- Check the production environment\n- Run the smoke tests\n- Share the release notes\n\nDepends on [[Review production configuration]].',
      blockedBy: ['config'],
      links: ['readme'],
      checklist: [
        { id: 'c1', title: 'Run production smoke tests', done: true },
        { id: 'c2', title: 'Publish the release', done: false },
        { id: 'c3', title: 'Update the changelog', done: false },
      ],
    }),
    makeTask('Fix Shipwreck authentication callback', {
      id: 'auth',
      stackId: 'oddware',
      scheduled: today(),
      tags: ['development'],
      priority: 1,
      notes: 'Handle the redirect after signing in with GitHub. Preserve the original destination.',
    }),
    makeTask('Review Port Authority timeline feature', {
      id: 'timeline',
      stackId: 'work',
      scheduled: today(),
      tags: ['design'],
      checklist: [
        { id: 'c4', title: 'Check empty state', done: true },
        { id: 'c5', title: 'Review keyboard interactions', done: false },
      ],
      links: ['auth'],
    }),
    makeTask('Finish the Repo Reaper README', {
      id: 'readme',
      stackId: 'oddware',
      scheduled: today(),
      completedAt: new Date().toISOString(),
      tags: ['writing'],
    }),
    makeTask('Call insurance', {
      id: 'insurance',
      stackId: 'personal',
      scheduled: today(),
      heading: 'Life & everything else',
      time: '14:00',
      notes: 'Ask about renewing the policy and the updated coverage options.',
      effort: 10,
    }),
    makeTask('Order groceries', {
      id: 'groceries',
      stackId: 'home',
      scheduled: today(),
      heading: 'Life & everything else',
      tags: ['errands'],
      checklist: [
        { id: 'g1', title: 'Oat milk', done: false },
        { id: 'g2', title: 'Fresh vegetables', done: false },
        { id: 'g3', title: 'Coffee beans', done: false },
      ],
    }),
    makeTask('Book a dentist appointment', {
      id: 'dentist',
      stackId: 'personal',
      scheduled: today(),
      heading: 'Life & everything else',
      completedAt: new Date().toISOString(),
    }),
    makeTask('Water the plants', {
      id: 'plants',
      stackId: 'home',
      scheduled: today(),
      heading: 'This evening',
      recurrence: 'every Tuesday',
      effort: 5,
    }),
    makeTask('A little reset for the office', {
      id: 'office',
      stackId: 'home',
      scheduled: today(),
      heading: 'This evening',
      effort: 15,
      notes: 'Clear the desk. Put things back in their place. Leave tomorrow a little space.',
    }),
    makeTask('Review production configuration', {
      id: 'config',
      stackId: 'oddware',
      completedAt: new Date().toISOString(),
      tags: ['development'],
    }),
    makeTask('Update portfolio screenshots', {
      id: 'portfolio',
      stackId: 'personal',
      scheduled: addDays(1),
      tags: ['design'],
      links: ['deploy'],
    }),
    makeTask('Sketch the next chapter for Deck', {
      id: 'deck-design',
      stackId: 'deck',
      scheduled: addDays(1),
      tags: ['design'],
      notes: 'Explore a calmer way to see how work connects.',
      links: ['graph-task'],
    }),
    makeTask('Explore graph interactions', {
      id: 'graph-task',
      stackId: 'deck',
      scheduled: addDays(2),
      tags: ['development'],
      blockedBy: ['deck-design'],
    }),
    makeTask('Send the weekly project update', {
      id: 'update',
      stackId: 'work',
      scheduled: addDays(3),
      tags: ['writing'],
      recurrence: 'every Friday',
    }),
    makeTask('Clean office', { id: 'clean', stackId: 'home', effort: 20 }),
    makeTask('Read about local-first software', {
      id: 'read',
      tags: ['reading'],
      destination: 'inbox',
      notes: 'A few ideas for making our tools more personal.',
    }),
    makeTask('That little bookstore on the corner', { id: 'bookstore', destination: 'inbox' }),
    makeTask('A better home for saved recipes', {
      id: 'recipes',
      destination: 'inbox',
      tags: ['ideas'],
    }),
    makeTask('Plan a long weekend away', {
      id: 'weekend',
      stackId: 'personal',
      destination: 'someday',
      tags: ['ideas'],
    }),
    makeTask('Build a reading nook', {
      id: 'nook',
      stackId: 'home',
      destination: 'someday',
      tags: ['ideas'],
    }),
    makeTask('Explore an offline reading mode', {
      id: 'reading-mode',
      stackId: 'deck',
      destination: 'someday',
    }),
    makeTask('Tidy up the design files', {
      id: 'designfiles',
      stackId: 'work',
      completedAt: new Date(addDays(-1) + 'T16:00:00').toISOString(),
    }),
  ].map((t, i) => ({ ...t, heading: t.heading || 'Focus today', order: i }));
  return {
    version: 1,
    tasks,
    stacks: [
      {
        id: 'oddware',
        name: 'Oddware',
        icon: '◈',
        color: '#b5a0d5',
        notes: 'Thoughtful little tools for the way we work.',
        deadline: null,
        headings: ['Development', 'Launch'],
        links: ['deck'],
      },
      {
        id: 'work',
        name: 'Work',
        icon: '▣',
        color: '#83a9be',
        notes: 'Good work, one thing at a time.',
        deadline: null,
        headings: ['In progress', 'Up next'],
        links: [],
      },
      {
        id: 'personal',
        name: 'Personal',
        icon: '☀',
        color: '#c9ae78',
        notes: 'Make room for life outside the screen.',
        deadline: null,
        headings: [],
        links: [],
      },
      {
        id: 'home',
        name: 'Home',
        icon: '⌂',
        color: '#91b49a',
        notes: 'A space to feel at home.',
        deadline: null,
        headings: [],
        links: [],
      },
      {
        id: 'deck',
        name: 'Deck',
        icon: '▱',
        color: '#bba5da',
        notes: 'Put what matters on deck.',
        deadline: null,
        headings: ['Design', 'Build'],
        links: [],
      },
    ],
    goals: [
      { id: 'launch-goal', title: 'Build things that matter', stackIds: ['oddware', 'deck'] },
    ],
    headings: ['Focus today', 'Life & everything else', 'This evening'],
    settings: { ...defaultSettings },
  };
}
