import type { LucideIcon } from 'lucide-react';
export interface StackIconInfo {
  id: string;
  label: string;
  category: string;
}
export const stackIconCatalog: StackIconInfo[] = [
  { id: 'lucide:layers-3', label: 'Layers', category: 'Projects' },
  { id: 'lucide:briefcase', label: 'Briefcase', category: 'Projects' },
  { id: 'lucide:briefcase-business', label: 'Briefcase Business', category: 'Projects' },
  { id: 'lucide:briefcase-conveyor-belt', label: 'Briefcase Conveyor Belt', category: 'Projects' },
  { id: 'lucide:briefcase-medical', label: 'Briefcase Medical', category: 'Projects' },
  { id: 'lucide:folder', label: 'Folder', category: 'Projects' },
  { id: 'lucide:folder-archive', label: 'Folder Archive', category: 'Projects' },
  { id: 'lucide:folder-check', label: 'Folder Check', category: 'Projects' },
  { id: 'lucide:folder-clock', label: 'Folder Clock', category: 'Projects' },
  { id: 'lucide:folder-closed', label: 'Folder Closed', category: 'Projects' },
  { id: 'lucide:folder-code', label: 'Folder Code', category: 'Projects' },
  { id: 'lucide:folder-cog', label: 'Folder Cog', category: 'Projects' },
  { id: 'lucide:folder-dot', label: 'Folder Dot', category: 'Projects' },
  { id: 'lucide:folder-down', label: 'Folder Down', category: 'Projects' },
  { id: 'lucide:folder-git', label: 'Folder Git', category: 'Projects' },
  { id: 'lucide:folder-git-2', label: 'Folder Git 2', category: 'Projects' },
  { id: 'lucide:folder-heart', label: 'Folder Heart', category: 'Projects' },
  { id: 'lucide:folder-input', label: 'Folder Input', category: 'Projects' },
  { id: 'lucide:folder-kanban', label: 'Folder Kanban', category: 'Projects' },
  { id: 'lucide:folder-key', label: 'Folder Key', category: 'Projects' },
  { id: 'lucide:folder-lock', label: 'Folder Lock', category: 'Projects' },
  { id: 'lucide:folder-minus', label: 'Folder Minus', category: 'Projects' },
  { id: 'lucide:folder-open', label: 'Folder Open', category: 'Projects' },
  { id: 'lucide:folder-open-dot', label: 'Folder Open Dot', category: 'Projects' },
  { id: 'lucide:folder-output', label: 'Folder Output', category: 'Projects' },
  { id: 'lucide:folder-plus', label: 'Folder Plus', category: 'Projects' },
  { id: 'lucide:folder-root', label: 'Folder Root', category: 'Projects' },
  { id: 'lucide:folder-search', label: 'Folder Search', category: 'Projects' },
  { id: 'lucide:folder-search-2', label: 'Folder Search 2', category: 'Projects' },
  { id: 'lucide:folder-symlink', label: 'Folder Symlink', category: 'Projects' },
  { id: 'lucide:folder-sync', label: 'Folder Sync', category: 'Projects' },
  { id: 'lucide:folder-tree', label: 'Folder Tree', category: 'Projects' },
  { id: 'lucide:folder-up', label: 'Folder Up', category: 'Projects' },
  { id: 'lucide:folder-x', label: 'Folder X', category: 'Projects' },
  { id: 'lucide:file', label: 'File', category: 'Projects' },
  { id: 'lucide:file-archive', label: 'File Archive', category: 'Projects' },
  { id: 'lucide:file-audio', label: 'File Audio', category: 'Projects' },
  { id: 'lucide:file-audio-2', label: 'File Audio 2', category: 'Projects' },
  { id: 'lucide:file-badge', label: 'File Badge', category: 'Projects' },
  { id: 'lucide:file-badge-2', label: 'File Badge 2', category: 'Projects' },
  { id: 'lucide:file-box', label: 'File Box', category: 'Projects' },
  { id: 'lucide:file-chart-line', label: 'File Chart Line', category: 'Projects' },
  { id: 'lucide:file-chart-pie', label: 'File Chart Pie', category: 'Projects' },
  { id: 'lucide:file-check', label: 'File Check', category: 'Projects' },
  { id: 'lucide:file-check-2', label: 'File Check 2', category: 'Projects' },
  { id: 'lucide:file-clock', label: 'File Clock', category: 'Projects' },
  { id: 'lucide:file-code', label: 'File Code', category: 'Projects' },
  { id: 'lucide:file-code-2', label: 'File Code 2', category: 'Projects' },
  { id: 'lucide:file-cog', label: 'File Cog', category: 'Projects' },
  { id: 'lucide:file-diff', label: 'File Diff', category: 'Projects' },
  { id: 'lucide:file-digit', label: 'File Digit', category: 'Projects' },
  { id: 'lucide:file-down', label: 'File Down', category: 'Projects' },
  { id: 'lucide:file-heart', label: 'File Heart', category: 'Projects' },
  { id: 'lucide:file-image', label: 'File Image', category: 'Projects' },
  { id: 'lucide:file-input', label: 'File Input', category: 'Projects' },
  { id: 'lucide:file-json', label: 'File Json', category: 'Projects' },
  { id: 'lucide:file-json-2', label: 'File Json 2', category: 'Projects' },
  { id: 'lucide:file-key', label: 'File Key', category: 'Projects' },
  { id: 'lucide:file-key-2', label: 'File Key 2', category: 'Projects' },
  { id: 'lucide:file-lock', label: 'File Lock', category: 'Projects' },
  { id: 'lucide:file-lock-2', label: 'File Lock 2', category: 'Projects' },
  { id: 'lucide:file-minus', label: 'File Minus', category: 'Projects' },
  { id: 'lucide:file-minus-2', label: 'File Minus 2', category: 'Projects' },
  { id: 'lucide:file-music', label: 'File Music', category: 'Projects' },
  { id: 'lucide:file-output', label: 'File Output', category: 'Projects' },
  { id: 'lucide:file-pen-line', label: 'File Pen Line', category: 'Projects' },
  { id: 'lucide:file-plus', label: 'File Plus', category: 'Projects' },
  { id: 'lucide:file-plus-2', label: 'File Plus 2', category: 'Projects' },
  { id: 'lucide:file-question', label: 'File Question', category: 'Projects' },
  { id: 'lucide:file-scan', label: 'File Scan', category: 'Projects' },
  { id: 'lucide:file-search', label: 'File Search', category: 'Projects' },
  { id: 'lucide:file-search-2', label: 'File Search 2', category: 'Projects' },
  { id: 'lucide:file-sliders', label: 'File Sliders', category: 'Projects' },
  { id: 'lucide:file-spreadsheet', label: 'File Spreadsheet', category: 'Projects' },
  { id: 'lucide:file-stack', label: 'File Stack', category: 'Projects' },
  { id: 'lucide:file-symlink', label: 'File Symlink', category: 'Projects' },
  { id: 'lucide:file-terminal', label: 'File Terminal', category: 'Projects' },
  { id: 'lucide:file-text', label: 'File Text', category: 'Projects' },
  { id: 'lucide:file-type', label: 'File Type', category: 'Projects' },
  { id: 'lucide:file-type-2', label: 'File Type 2', category: 'Projects' },
  { id: 'lucide:file-up', label: 'File Up', category: 'Projects' },
  { id: 'lucide:file-user', label: 'File User', category: 'Projects' },
  { id: 'lucide:file-video', label: 'File Video', category: 'Projects' },
  { id: 'lucide:file-video-2', label: 'File Video 2', category: 'Projects' },
  { id: 'lucide:file-volume', label: 'File Volume', category: 'Projects' },
  { id: 'lucide:file-volume-2', label: 'File Volume 2', category: 'Projects' },
  { id: 'lucide:file-warning', label: 'File Warning', category: 'Projects' },
  { id: 'lucide:file-x', label: 'File X', category: 'Projects' },
  { id: 'lucide:file-x-2', label: 'File X 2', category: 'Projects' },
  { id: 'lucide:clipboard', label: 'Clipboard', category: 'Projects' },
  { id: 'lucide:clipboard-check', label: 'Clipboard Check', category: 'Projects' },
  { id: 'lucide:clipboard-copy', label: 'Clipboard Copy', category: 'Projects' },
  { id: 'lucide:clipboard-list', label: 'Clipboard List', category: 'Projects' },
  { id: 'lucide:clipboard-minus', label: 'Clipboard Minus', category: 'Projects' },
  { id: 'lucide:clipboard-paste', label: 'Clipboard Paste', category: 'Projects' },
  { id: 'lucide:clipboard-pen-line', label: 'Clipboard Pen Line', category: 'Projects' },
  { id: 'lucide:clipboard-plus', label: 'Clipboard Plus', category: 'Projects' },
  { id: 'lucide:clipboard-type', label: 'Clipboard Type', category: 'Projects' },
  { id: 'lucide:clipboard-x', label: 'Clipboard X', category: 'Projects' },
  { id: 'lucide:book', label: 'Book', category: 'Projects' },
  { id: 'lucide:book-a', label: 'Book A', category: 'Projects' },
  { id: 'lucide:book-audio', label: 'Book Audio', category: 'Projects' },
  { id: 'lucide:book-check', label: 'Book Check', category: 'Projects' },
  { id: 'lucide:book-copy', label: 'Book Copy', category: 'Projects' },
  { id: 'lucide:book-dashed', label: 'Book Dashed', category: 'Projects' },
  { id: 'lucide:book-down', label: 'Book Down', category: 'Projects' },
  { id: 'lucide:book-headphones', label: 'Book Headphones', category: 'Projects' },
  { id: 'lucide:book-heart', label: 'Book Heart', category: 'Projects' },
  { id: 'lucide:book-image', label: 'Book Image', category: 'Projects' },
  { id: 'lucide:book-key', label: 'Book Key', category: 'Projects' },
  { id: 'lucide:book-lock', label: 'Book Lock', category: 'Projects' },
  { id: 'lucide:book-marked', label: 'Book Marked', category: 'Projects' },
  { id: 'lucide:book-minus', label: 'Book Minus', category: 'Projects' },
  { id: 'lucide:book-open', label: 'Book Open', category: 'Projects' },
  { id: 'lucide:book-open-check', label: 'Book Open Check', category: 'Projects' },
  { id: 'lucide:book-open-text', label: 'Book Open Text', category: 'Projects' },
  { id: 'lucide:book-plus', label: 'Book Plus', category: 'Projects' },
  { id: 'lucide:book-text', label: 'Book Text', category: 'Projects' },
  { id: 'lucide:book-type', label: 'Book Type', category: 'Projects' },
  { id: 'lucide:book-up', label: 'Book Up', category: 'Projects' },
  { id: 'lucide:book-up-2', label: 'Book Up 2', category: 'Projects' },
  { id: 'lucide:book-user', label: 'Book User', category: 'Projects' },
  { id: 'lucide:book-x', label: 'Book X', category: 'Projects' },
  { id: 'lucide:library', label: 'Library', category: 'Projects' },
  { id: 'lucide:library-big', label: 'Library Big', category: 'Projects' },
  { id: 'lucide:kanban', label: 'Kanban', category: 'Projects' },
  { id: 'lucide:code', label: 'Code', category: 'Projects' },
  { id: 'lucide:database', label: 'Database', category: 'Projects' },
  { id: 'lucide:database-backup', label: 'Database Backup', category: 'Projects' },
  { id: 'lucide:database-zap', label: 'Database Zap', category: 'Projects' },
  { id: 'lucide:cloud', label: 'Cloud', category: 'Projects' },
  { id: 'lucide:cloud-alert', label: 'Cloud Alert', category: 'Projects' },
  { id: 'lucide:cloud-cog', label: 'Cloud Cog', category: 'Projects' },
  { id: 'lucide:cloud-download', label: 'Cloud Download', category: 'Projects' },
  { id: 'lucide:cloud-drizzle', label: 'Cloud Drizzle', category: 'Projects' },
  { id: 'lucide:cloud-fog', label: 'Cloud Fog', category: 'Projects' },
  { id: 'lucide:cloud-hail', label: 'Cloud Hail', category: 'Projects' },
  { id: 'lucide:cloud-lightning', label: 'Cloud Lightning', category: 'Projects' },
  { id: 'lucide:cloud-moon', label: 'Cloud Moon', category: 'Projects' },
  { id: 'lucide:cloud-moon-rain', label: 'Cloud Moon Rain', category: 'Projects' },
  { id: 'lucide:cloud-off', label: 'Cloud Off', category: 'Projects' },
  { id: 'lucide:cloud-rain', label: 'Cloud Rain', category: 'Projects' },
  { id: 'lucide:cloud-rain-wind', label: 'Cloud Rain Wind', category: 'Projects' },
  { id: 'lucide:cloud-snow', label: 'Cloud Snow', category: 'Projects' },
  { id: 'lucide:cloud-sun', label: 'Cloud Sun', category: 'Projects' },
  { id: 'lucide:cloud-sun-rain', label: 'Cloud Sun Rain', category: 'Projects' },
  { id: 'lucide:cloud-upload', label: 'Cloud Upload', category: 'Projects' },
  { id: 'lucide:chart-network', label: 'Chart Network', category: 'Projects' },
  { id: 'lucide:bug', label: 'Bug', category: 'Projects' },
  { id: 'lucide:bug-off', label: 'Bug Off', category: 'Projects' },
  { id: 'lucide:bug-play', label: 'Bug Play', category: 'Projects' },
  { id: 'lucide:boom-box', label: 'Boom Box', category: 'Projects' },
  { id: 'lucide:box', label: 'Box', category: 'Projects' },
  { id: 'lucide:bookmark', label: 'Bookmark', category: 'Projects' },
  { id: 'lucide:bookmark-check', label: 'Bookmark Check', category: 'Projects' },
  { id: 'lucide:bookmark-minus', label: 'Bookmark Minus', category: 'Projects' },
  { id: 'lucide:bookmark-plus', label: 'Bookmark Plus', category: 'Projects' },
  { id: 'lucide:bookmark-x', label: 'Bookmark X', category: 'Projects' },
  { id: 'lucide:calendar-search', label: 'Calendar Search', category: 'Projects' },
  { id: 'lucide:hammer', label: 'Hammer', category: 'Projects' },
  { id: 'lucide:calendar', label: 'Calendar', category: 'Projects' },
  { id: 'lucide:calendar-1', label: 'Calendar 1', category: 'Projects' },
  { id: 'lucide:calendar-arrow-down', label: 'Calendar Arrow Down', category: 'Projects' },
  { id: 'lucide:calendar-arrow-up', label: 'Calendar Arrow Up', category: 'Projects' },
  { id: 'lucide:calendar-check', label: 'Calendar Check', category: 'Projects' },
  { id: 'lucide:calendar-check-2', label: 'Calendar Check 2', category: 'Projects' },
  { id: 'lucide:calendar-clock', label: 'Calendar Clock', category: 'Projects' },
  { id: 'lucide:calendar-cog', label: 'Calendar Cog', category: 'Projects' },
  { id: 'lucide:calendar-days', label: 'Calendar Days', category: 'Projects' },
  { id: 'lucide:calendar-fold', label: 'Calendar Fold', category: 'Projects' },
  { id: 'lucide:calendar-heart', label: 'Calendar Heart', category: 'Projects' },
  { id: 'lucide:calendar-minus', label: 'Calendar Minus', category: 'Projects' },
  { id: 'lucide:calendar-minus-2', label: 'Calendar Minus 2', category: 'Projects' },
  { id: 'lucide:calendar-off', label: 'Calendar Off', category: 'Projects' },
  { id: 'lucide:calendar-plus', label: 'Calendar Plus', category: 'Projects' },
  { id: 'lucide:calendar-plus-2', label: 'Calendar Plus 2', category: 'Projects' },
  { id: 'lucide:calendar-range', label: 'Calendar Range', category: 'Projects' },
  { id: 'lucide:calendar-sync', label: 'Calendar Sync', category: 'Projects' },
  { id: 'lucide:calendar-x', label: 'Calendar X', category: 'Projects' },
  { id: 'lucide:calendar-x-2', label: 'Calendar X 2', category: 'Projects' },
  { id: 'lucide:alarm-clock', label: 'Alarm Clock', category: 'Projects' },
  { id: 'lucide:house-plug', label: 'House Plug', category: 'Home & life' },
  { id: 'lucide:house-plus', label: 'House Plus', category: 'Home & life' },
  { id: 'lucide:bed', label: 'Bed', category: 'Home & life' },
  { id: 'lucide:bed-double', label: 'Bed Double', category: 'Home & life' },
  { id: 'lucide:bed-single', label: 'Bed Single', category: 'Home & life' },
  { id: 'lucide:lamp', label: 'Lamp', category: 'Home & life' },
  { id: 'lucide:lamp-ceiling', label: 'Lamp Ceiling', category: 'Home & life' },
  { id: 'lucide:lamp-desk', label: 'Lamp Desk', category: 'Home & life' },
  { id: 'lucide:lamp-floor', label: 'Lamp Floor', category: 'Home & life' },
  { id: 'lucide:lamp-wall-down', label: 'Lamp Wall Down', category: 'Home & life' },
  { id: 'lucide:lamp-wall-up', label: 'Lamp Wall Up', category: 'Home & life' },
  { id: 'lucide:armchair', label: 'Armchair', category: 'Home & life' },
  { id: 'lucide:door-closed', label: 'Door Closed', category: 'Home & life' },
  { id: 'lucide:door-open', label: 'Door Open', category: 'Home & life' },
  { id: 'lucide:key', label: 'Key', category: 'Home & life' },
  { id: 'lucide:key-round', label: 'Key Round', category: 'Home & life' },
  { id: 'lucide:key-square', label: 'Key Square', category: 'Home & life' },
  { id: 'lucide:bath', label: 'Bath', category: 'Home & life' },
  { id: 'lucide:coffee', label: 'Coffee', category: 'Home & life' },
  { id: 'lucide:cake', label: 'Cake', category: 'Home & life' },
  { id: 'lucide:cake-slice', label: 'Cake Slice', category: 'Home & life' },
  { id: 'lucide:cookie', label: 'Cookie', category: 'Home & life' },
  { id: 'lucide:apple', label: 'Apple', category: 'Home & life' },
  { id: 'lucide:banana', label: 'Banana', category: 'Home & life' },
  { id: 'lucide:carrot', label: 'Carrot', category: 'Home & life' },
  { id: 'lucide:fish', label: 'Fish', category: 'Home & life' },
  { id: 'lucide:fish-off', label: 'Fish Off', category: 'Home & life' },
  { id: 'lucide:fish-symbol', label: 'Fish Symbol', category: 'Home & life' },
  { id: 'lucide:beef', label: 'Beef', category: 'Home & life' },
  { id: 'lucide:baby', label: 'Baby', category: 'Home & life' },
  { id: 'lucide:cat', label: 'Cat', category: 'Home & life' },
  { id: 'lucide:bird', label: 'Bird', category: 'Home & life' },
  { id: 'lucide:hand-heart', label: 'Hand Heart', category: 'Home & life' },
  { id: 'lucide:heart', label: 'Heart', category: 'Home & life' },
  { id: 'lucide:heart-crack', label: 'Heart Crack', category: 'Home & life' },
  { id: 'lucide:heart-handshake', label: 'Heart Handshake', category: 'Home & life' },
  { id: 'lucide:heart-off', label: 'Heart Off', category: 'Home & life' },
  { id: 'lucide:heart-pulse', label: 'Heart Pulse', category: 'Home & life' },
  { id: 'lucide:hand', label: 'Hand', category: 'Home & life' },
  { id: 'lucide:hand-coins', label: 'Hand Coins', category: 'Home & life' },
  { id: 'lucide:hand-helping', label: 'Hand Helping', category: 'Home & life' },
  { id: 'lucide:hand-metal', label: 'Hand Metal', category: 'Home & life' },
  { id: 'lucide:hand-platter', label: 'Hand Platter', category: 'Home & life' },
  { id: 'lucide:circle-user', label: 'Circle User', category: 'Home & life' },
  { id: 'lucide:circle-user-round', label: 'Circle User Round', category: 'Home & life' },
  { id: 'lucide:accessibility', label: 'Accessibility', category: 'Home & life' },
  { id: 'lucide:laugh', label: 'Laugh', category: 'Home & life' },
  { id: 'lucide:glasses', label: 'Glasses', category: 'Home & life' },
  { id: 'lucide:dumbbell', label: 'Dumbbell', category: 'Home & life' },
  { id: 'lucide:bike', label: 'Bike', category: 'Home & life' },
  { id: 'lucide:cable-car', label: 'Cable Car', category: 'Home & life' },
  { id: 'lucide:car', label: 'Car', category: 'Home & life' },
  { id: 'lucide:car-front', label: 'Car Front', category: 'Home & life' },
  { id: 'lucide:car-taxi-front', label: 'Car Taxi Front', category: 'Home & life' },
  { id: 'lucide:bus', label: 'Bus', category: 'Home & life' },
  { id: 'lucide:bus-front', label: 'Bus Front', category: 'Home & life' },
  { id: 'lucide:list-tree', label: 'List Tree', category: 'Home & life' },
  { id: 'lucide:flower', label: 'Flower', category: 'Home & life' },
  { id: 'lucide:flower-2', label: 'Flower 2', category: 'Home & life' },
  { id: 'lucide:leaf', label: 'Leaf', category: 'Home & life' },
  { id: 'lucide:gift', label: 'Gift', category: 'Home & life' },
  { id: 'lucide:keyboard-music', label: 'Keyboard Music', category: 'Home & life' },
  { id: 'lucide:list-music', label: 'List Music', category: 'Home & life' },
  { id: 'lucide:headphones', label: 'Headphones', category: 'Home & life' },
  { id: 'lucide:gamepad', label: 'Gamepad', category: 'Home & life' },
  { id: 'lucide:gamepad-2', label: 'Gamepad 2', category: 'Home & life' },
  { id: 'lucide:dice-1', label: 'Dice 1', category: 'Home & life' },
  { id: 'lucide:dice-2', label: 'Dice 2', category: 'Home & life' },
  { id: 'lucide:dice-3', label: 'Dice 3', category: 'Home & life' },
  { id: 'lucide:dice-4', label: 'Dice 4', category: 'Home & life' },
  { id: 'lucide:dice-5', label: 'Dice 5', category: 'Home & life' },
  { id: 'lucide:dice-6', label: 'Dice 6', category: 'Home & life' },
  { id: 'lucide:brush', label: 'Brush', category: 'Home & life' },
  { id: 'lucide:cross', label: 'Cross', category: 'Home & life' },
  { id: 'lucide:activity', label: 'Activity', category: 'Home & life' },
  { id: 'lucide:fence', label: 'Fence', category: 'Home & life' },
  { id: 'lucide:egg', label: 'Egg', category: 'Home & life' },
  { id: 'lucide:egg-fried', label: 'Egg Fried', category: 'Home & life' },
  { id: 'lucide:egg-off', label: 'Egg Off', category: 'Home & life' },
  { id: 'lucide:croissant', label: 'Croissant', category: 'Home & life' },
  { id: 'lucide:candy', label: 'Candy', category: 'Home & life' },
  { id: 'lucide:candy-cane', label: 'Candy Cane', category: 'Home & life' },
  { id: 'lucide:candy-off', label: 'Candy Off', category: 'Home & life' },
  { id: 'lucide:donut', label: 'Donut', category: 'Home & life' },
  { id: 'lucide:beer', label: 'Beer', category: 'Home & life' },
  { id: 'lucide:beer-off', label: 'Beer Off', category: 'Home & life' },
  { id: 'lucide:bone', label: 'Bone', category: 'Home & life' },
  { id: 'lucide:handshake', label: 'Handshake', category: 'Home & life' },
  { id: 'lucide:contact', label: 'Contact', category: 'Home & life' },
  { id: 'lucide:footprints', label: 'Footprints', category: 'Home & life' },
  { id: 'lucide:clover', label: 'Clover', category: 'Home & life' },
  { id: 'lucide:glass-water', label: 'Glass Water', category: 'Home & life' },
  { id: 'lucide:dog', label: 'Dog', category: 'Home & life' },
  { id: 'lucide:circle', label: 'Circle', category: 'Explore' },
  { id: 'lucide:circle-dashed', label: 'Circle Dashed', category: 'Explore' },
  { id: 'lucide:circle-divide', label: 'Circle Divide', category: 'Explore' },
  { id: 'lucide:circle-dollar-sign', label: 'Circle Dollar Sign', category: 'Explore' },
  { id: 'lucide:circle-dot', label: 'Circle Dot', category: 'Explore' },
  { id: 'lucide:circle-dot-dashed', label: 'Circle Dot Dashed', category: 'Explore' },
  { id: 'lucide:circle-ellipsis', label: 'Circle Ellipsis', category: 'Explore' },
  { id: 'lucide:circle-equal', label: 'Circle Equal', category: 'Explore' },
  { id: 'lucide:circle-fading-arrow-up', label: 'Circle Fading Arrow Up', category: 'Explore' },
  { id: 'lucide:circle-fading-plus', label: 'Circle Fading Plus', category: 'Explore' },
  { id: 'lucide:circle-gauge', label: 'Circle Gauge', category: 'Explore' },
  { id: 'lucide:circle-help', label: 'Circle Help', category: 'Explore' },
  { id: 'lucide:circle-minus', label: 'Circle Minus', category: 'Explore' },
  { id: 'lucide:circle-off', label: 'Circle Off', category: 'Explore' },
  { id: 'lucide:circle-parking', label: 'Circle Parking', category: 'Explore' },
  { id: 'lucide:circle-parking-off', label: 'Circle Parking Off', category: 'Explore' },
  { id: 'lucide:circle-pause', label: 'Circle Pause', category: 'Explore' },
  { id: 'lucide:circle-percent', label: 'Circle Percent', category: 'Explore' },
  { id: 'lucide:circle-play', label: 'Circle Play', category: 'Explore' },
  { id: 'lucide:circle-plus', label: 'Circle Plus', category: 'Explore' },
  { id: 'lucide:circle-power', label: 'Circle Power', category: 'Explore' },
  { id: 'lucide:circle-slash', label: 'Circle Slash', category: 'Explore' },
  { id: 'lucide:circle-slash-2', label: 'Circle Slash 2', category: 'Explore' },
  { id: 'lucide:circle-stop', label: 'Circle Stop', category: 'Explore' },
  { id: 'lucide:circle-x', label: 'Circle X', category: 'Explore' },
  { id: 'lucide:bot-message-square', label: 'Bot Message Square', category: 'Explore' },
  { id: 'lucide:flag-triangle-left', label: 'Flag Triangle Left', category: 'Explore' },
  { id: 'lucide:flag-triangle-right', label: 'Flag Triangle Right', category: 'Explore' },
  { id: 'lucide:hexagon', label: 'Hexagon', category: 'Explore' },
  { id: 'lucide:diamond', label: 'Diamond', category: 'Explore' },
  { id: 'lucide:diamond-minus', label: 'Diamond Minus', category: 'Explore' },
  { id: 'lucide:diamond-percent', label: 'Diamond Percent', category: 'Explore' },
  { id: 'lucide:diamond-plus', label: 'Diamond Plus', category: 'Explore' },
  { id: 'lucide:lightbulb', label: 'Lightbulb', category: 'Explore' },
  { id: 'lucide:lightbulb-off', label: 'Lightbulb Off', category: 'Explore' },
  { id: 'lucide:flame', label: 'Flame', category: 'Explore' },
  { id: 'lucide:flame-kindling', label: 'Flame Kindling', category: 'Explore' },
  { id: 'lucide:bolt', label: 'Bolt', category: 'Explore' },
  { id: 'lucide:earth-lock', label: 'Earth Lock', category: 'Explore' },
  { id: 'lucide:globe-lock', label: 'Globe Lock', category: 'Explore' },
  { id: 'lucide:lock', label: 'Lock', category: 'Explore' },
  { id: 'lucide:lock-keyhole', label: 'Lock Keyhole', category: 'Explore' },
  { id: 'lucide:lock-keyhole-open', label: 'Lock Keyhole Open', category: 'Explore' },
  { id: 'lucide:lock-open', label: 'Lock Open', category: 'Explore' },
  { id: 'lucide:flag', label: 'Flag', category: 'Explore' },
  { id: 'lucide:flag-off', label: 'Flag Off', category: 'Explore' },
  { id: 'lucide:award', label: 'Award', category: 'Explore' },
  { id: 'lucide:crown', label: 'Crown', category: 'Explore' },
  { id: 'lucide:gem', label: 'Gem', category: 'Explore' },
  { id: 'lucide:badge', label: 'Badge', category: 'Explore' },
  { id: 'lucide:badge-alert', label: 'Badge Alert', category: 'Explore' },
  { id: 'lucide:badge-cent', label: 'Badge Cent', category: 'Explore' },
  { id: 'lucide:badge-check', label: 'Badge Check', category: 'Explore' },
  { id: 'lucide:badge-dollar-sign', label: 'Badge Dollar Sign', category: 'Explore' },
  { id: 'lucide:badge-euro', label: 'Badge Euro', category: 'Explore' },
  { id: 'lucide:badge-help', label: 'Badge Help', category: 'Explore' },
  { id: 'lucide:badge-indian-rupee', label: 'Badge Indian Rupee', category: 'Explore' },
  { id: 'lucide:badge-info', label: 'Badge Info', category: 'Explore' },
  { id: 'lucide:badge-japanese-yen', label: 'Badge Japanese Yen', category: 'Explore' },
  { id: 'lucide:badge-minus', label: 'Badge Minus', category: 'Explore' },
  { id: 'lucide:badge-percent', label: 'Badge Percent', category: 'Explore' },
  { id: 'lucide:badge-plus', label: 'Badge Plus', category: 'Explore' },
  { id: 'lucide:badge-pound-sterling', label: 'Badge Pound Sterling', category: 'Explore' },
  { id: 'lucide:badge-russian-ruble', label: 'Badge Russian Ruble', category: 'Explore' },
  { id: 'lucide:badge-swiss-franc', label: 'Badge Swiss Franc', category: 'Explore' },
  { id: 'lucide:badge-x', label: 'Badge X', category: 'Explore' },
  { id: 'lucide:eye', label: 'Eye', category: 'Explore' },
  { id: 'lucide:eye-closed', label: 'Eye Closed', category: 'Explore' },
  { id: 'lucide:eye-off', label: 'Eye Off', category: 'Explore' },
  { id: 'lucide:bluetooth', label: 'Bluetooth', category: 'Explore' },
  { id: 'lucide:bluetooth-connected', label: 'Bluetooth Connected', category: 'Explore' },
  { id: 'lucide:bluetooth-off', label: 'Bluetooth Off', category: 'Explore' },
  { id: 'lucide:bluetooth-searching', label: 'Bluetooth Searching', category: 'Explore' },
  { id: 'lucide:battery', label: 'Battery', category: 'Explore' },
  { id: 'lucide:battery-charging', label: 'Battery Charging', category: 'Explore' },
  { id: 'lucide:battery-full', label: 'Battery Full', category: 'Explore' },
  { id: 'lucide:battery-low', label: 'Battery Low', category: 'Explore' },
  { id: 'lucide:battery-medium', label: 'Battery Medium', category: 'Explore' },
  { id: 'lucide:battery-warning', label: 'Battery Warning', category: 'Explore' },
  { id: 'lucide:atom', label: 'Atom', category: 'Explore' },
  { id: 'lucide:flask-conical', label: 'Flask Conical', category: 'Explore' },
  { id: 'lucide:flask-conical-off', label: 'Flask Conical Off', category: 'Explore' },
  { id: 'lucide:flask-round', label: 'Flask Round', category: 'Explore' },
  { id: 'lucide:beaker', label: 'Beaker', category: 'Explore' },
  { id: 'lucide:dna', label: 'Dna', category: 'Explore' },
  { id: 'lucide:dna-off', label: 'Dna Off', category: 'Explore' },
  { id: 'lucide:anchor', label: 'Anchor', category: 'Explore' },
  { id: 'lucide:castle', label: 'Castle', category: 'Explore' },
  { id: 'lucide:landmark', label: 'Landmark', category: 'Explore' },
  { id: 'lucide:church', label: 'Church', category: 'Explore' },
  { id: 'lucide:factory', label: 'Factory', category: 'Explore' },
  { id: 'lucide:coins', label: 'Coins', category: 'Explore' },
  { id: 'lucide:calculator', label: 'Calculator', category: 'Explore' },
  { id: 'lucide:gauge', label: 'Gauge', category: 'Explore' },
  { id: 'lucide:hourglass', label: 'Hourglass', category: 'Explore' },
  { id: 'lucide:alarm-clock-minus', label: 'Alarm Clock Minus', category: 'Explore' },
  { id: 'lucide:alarm-clock-off', label: 'Alarm Clock Off', category: 'Explore' },
  { id: 'lucide:alarm-clock-plus', label: 'Alarm Clock Plus', category: 'Explore' },
  { id: 'lucide:alarm-smoke', label: 'Alarm Smoke', category: 'Explore' },
  { id: 'lucide:history', label: 'History', category: 'Explore' },
  { id: 'lucide:expand', label: 'Expand', category: 'Explore' },
  { id: 'lucide:a-arrow-down', label: 'A Arrow Down', category: 'Explore' },
  { id: 'lucide:a-arrow-up', label: 'A Arrow Up', category: 'Explore' },
  { id: 'lucide:arrow-big-down', label: 'Arrow Big Down', category: 'Explore' },
  { id: 'lucide:arrow-big-down-dash', label: 'Arrow Big Down Dash', category: 'Explore' },
  { id: 'lucide:arrow-big-left', label: 'Arrow Big Left', category: 'Explore' },
  { id: 'lucide:arrow-big-left-dash', label: 'Arrow Big Left Dash', category: 'Explore' },
  { id: 'lucide:arrow-big-right', label: 'Arrow Big Right', category: 'Explore' },
  { id: 'lucide:arrow-big-right-dash', label: 'Arrow Big Right Dash', category: 'Explore' },
  { id: 'lucide:arrow-big-up', label: 'Arrow Big Up', category: 'Explore' },
  { id: 'lucide:arrow-big-up-dash', label: 'Arrow Big Up Dash', category: 'Explore' },
  { id: 'lucide:arrow-down', label: 'Arrow Down', category: 'Explore' },
  { id: 'lucide:arrow-down-0-1', label: 'Arrow Down 0 1', category: 'Explore' },
  { id: 'lucide:arrow-down-1-0', label: 'Arrow Down 1 0', category: 'Explore' },
  { id: 'lucide:arrow-down-a-z', label: 'Arrow Down A Z', category: 'Explore' },
  { id: 'lucide:arrow-down-from-line', label: 'Arrow Down From Line', category: 'Explore' },
  { id: 'lucide:arrow-down-left', label: 'Arrow Down Left', category: 'Explore' },
  { id: 'lucide:arrow-down-narrow-wide', label: 'Arrow Down Narrow Wide', category: 'Explore' },
  { id: 'lucide:arrow-down-right', label: 'Arrow Down Right', category: 'Explore' },
  { id: 'lucide:arrow-down-to-dot', label: 'Arrow Down To Dot', category: 'Explore' },
  { id: 'lucide:arrow-down-to-line', label: 'Arrow Down To Line', category: 'Explore' },
  { id: 'lucide:arrow-down-up', label: 'Arrow Down Up', category: 'Explore' },
  { id: 'lucide:arrow-down-wide-narrow', label: 'Arrow Down Wide Narrow', category: 'Explore' },
  { id: 'lucide:arrow-down-z-a', label: 'Arrow Down Z A', category: 'Explore' },
  { id: 'lucide:arrow-left', label: 'Arrow Left', category: 'Explore' },
  { id: 'lucide:arrow-left-from-line', label: 'Arrow Left From Line', category: 'Explore' },
  { id: 'lucide:arrow-left-right', label: 'Arrow Left Right', category: 'Explore' },
  { id: 'lucide:arrow-left-to-line', label: 'Arrow Left To Line', category: 'Explore' },
  { id: 'lucide:arrow-right', label: 'Arrow Right', category: 'Explore' },
  { id: 'lucide:arrow-right-from-line', label: 'Arrow Right From Line', category: 'Explore' },
  { id: 'lucide:arrow-right-left', label: 'Arrow Right Left', category: 'Explore' },
  { id: 'lucide:arrow-right-to-line', label: 'Arrow Right To Line', category: 'Explore' },
  { id: 'lucide:arrow-up', label: 'Arrow Up', category: 'Explore' },
  { id: 'lucide:arrow-up-0-1', label: 'Arrow Up 0 1', category: 'Explore' },
  { id: 'lucide:arrow-up-1-0', label: 'Arrow Up 1 0', category: 'Explore' },
  { id: 'lucide:arrow-up-a-z', label: 'Arrow Up A Z', category: 'Explore' },
  { id: 'lucide:arrow-up-down', label: 'Arrow Up Down', category: 'Explore' },
  { id: 'lucide:arrow-up-from-dot', label: 'Arrow Up From Dot', category: 'Explore' },
  { id: 'lucide:arrow-up-from-line', label: 'Arrow Up From Line', category: 'Explore' },
  { id: 'lucide:arrow-up-left', label: 'Arrow Up Left', category: 'Explore' },
  { id: 'lucide:arrow-up-narrow-wide', label: 'Arrow Up Narrow Wide', category: 'Explore' },
  { id: 'lucide:arrow-up-right', label: 'Arrow Up Right', category: 'Explore' },
  { id: 'lucide:arrow-up-to-line', label: 'Arrow Up To Line', category: 'Explore' },
  { id: 'lucide:arrow-up-wide-narrow', label: 'Arrow Up Wide Narrow', category: 'Explore' },
  { id: 'lucide:arrow-up-z-a', label: 'Arrow Up Z A', category: 'Explore' },
  { id: 'lucide:clock-arrow-down', label: 'Clock Arrow Down', category: 'Explore' },
  { id: 'lucide:clock-arrow-up', label: 'Clock Arrow Up', category: 'Explore' },
  { id: 'lucide:git-pull-request-arrow', label: 'Git Pull Request Arrow', category: 'Explore' },
  {
    id: 'lucide:git-pull-request-create-arrow',
    label: 'Git Pull Request Create Arrow',
    category: 'Explore',
  },
  { id: 'lucide:chevron-down', label: 'Chevron Down', category: 'Explore' },
  { id: 'lucide:chevron-first', label: 'Chevron First', category: 'Explore' },
  { id: 'lucide:chevron-last', label: 'Chevron Last', category: 'Explore' },
  { id: 'lucide:chevron-left', label: 'Chevron Left', category: 'Explore' },
  { id: 'lucide:chevron-right', label: 'Chevron Right', category: 'Explore' },
  { id: 'lucide:chevron-up', label: 'Chevron Up', category: 'Explore' },
];
const byId = new Map(stackIconCatalog.map((entry) => [entry.id, entry]));
export const stackIconEntry = (value: string) => byId.get(value);
export const stackIconCategory = (value: string) => byId.get(value)?.category;
export const stackIconName = (value: string) =>
  value.startsWith('lucide:') ? value.slice(7) : value;
const loaders: Record<string, () => Promise<{ icons: Record<string, LucideIcon> }>> = {
  Projects: () => import('./stack-icons/projects'),
  'Home & life': () => import('./stack-icons/home-life'),
  Explore: () => import('./stack-icons/explore'),
};
const cache = new Map<string, Promise<Record<string, LucideIcon>>>();
export function loadStackIconCategory(category: string): Promise<Record<string, LucideIcon>> {
  let group = cache.get(category);
  if (!group) {
    const loader = loaders[category];
    if (!loader) return Promise.resolve({} as Record<string, LucideIcon>);
    group = loader()
      .then((module) => module.icons)
      .catch((error: unknown) => {
        cache.delete(category);
        throw error;
      });
    cache.set(category, group);
  }
  return group;
}
export async function loadStackIcon(value: string) {
  const category = stackIconCategory(value);
  if (!category) return undefined;
  return (await loadStackIconCategory(category))[stackIconName(value)];
}
