import {
  AArrowDown,
  AArrowUp,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlarmSmoke,
  Anchor,
  ArrowBigDown,
  ArrowBigDownDash,
  ArrowBigLeft,
  ArrowBigLeftDash,
  ArrowBigRight,
  ArrowBigRightDash,
  ArrowBigUp,
  ArrowBigUpDash,
  ArrowDown,
  ArrowDown01,
  ArrowDown10,
  ArrowDownAZ,
  ArrowDownFromLine,
  ArrowDownLeft,
  ArrowDownNarrowWide,
  ArrowDownRight,
  ArrowDownToDot,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowDownZA,
  ArrowLeft,
  ArrowLeftFromLine,
  ArrowLeftRight,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightFromLine,
  ArrowRightLeft,
  ArrowRightToLine,
  ArrowUp,
  ArrowUp01,
  ArrowUp10,
  ArrowUpAZ,
  ArrowUpDown,
  ArrowUpFromDot,
  ArrowUpFromLine,
  ArrowUpLeft,
  ArrowUpNarrowWide,
  ArrowUpRight,
  ArrowUpToLine,
  ArrowUpWideNarrow,
  ArrowUpZA,
  Atom,
  Award,
  Badge,
  BadgeAlert,
  BadgeCent,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  BadgeHelp,
  BadgeIndianRupee,
  BadgeInfo,
  BadgeJapaneseYen,
  BadgeMinus,
  BadgePercent,
  BadgePlus,
  BadgePoundSterling,
  BadgeRussianRuble,
  BadgeSwissFranc,
  BadgeX,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Beaker,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bolt,
  BotMessageSquare,
  Calculator,
  Castle,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Church,
  Circle,
  CircleDashed,
  CircleDivide,
  CircleDollarSign,
  CircleDot,
  CircleDotDashed,
  CircleEllipsis,
  CircleEqual,
  CircleFadingArrowUp,
  CircleFadingPlus,
  CircleGauge,
  CircleHelp,
  CircleMinus,
  CircleOff,
  CircleParking,
  CircleParkingOff,
  CirclePause,
  CirclePercent,
  CirclePlay,
  CirclePlus,
  CirclePower,
  CircleSlash,
  CircleSlash2,
  CircleStop,
  CircleX,
  ClockArrowDown,
  ClockArrowUp,
  Coins,
  Crown,
  Diamond,
  DiamondMinus,
  DiamondPercent,
  DiamondPlus,
  Dna,
  DnaOff,
  EarthLock,
  Expand,
  Eye,
  EyeClosed,
  EyeOff,
  Factory,
  Flag,
  FlagOff,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  FlameKindling,
  FlaskConical,
  FlaskConicalOff,
  FlaskRound,
  Gauge,
  Gem,
  GitPullRequestArrow,
  GitPullRequestCreateArrow,
  GlobeLock,
  Hexagon,
  History,
  Hourglass,
  Landmark,
  Lightbulb,
  LightbulbOff,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
export const icons: Record<string, LucideIcon> = {
  circle: Circle,
  'circle-dashed': CircleDashed,
  'circle-divide': CircleDivide,
  'circle-dollar-sign': CircleDollarSign,
  'circle-dot': CircleDot,
  'circle-dot-dashed': CircleDotDashed,
  'circle-ellipsis': CircleEllipsis,
  'circle-equal': CircleEqual,
  'circle-fading-arrow-up': CircleFadingArrowUp,
  'circle-fading-plus': CircleFadingPlus,
  'circle-gauge': CircleGauge,
  'circle-help': CircleHelp,
  'circle-minus': CircleMinus,
  'circle-off': CircleOff,
  'circle-parking': CircleParking,
  'circle-parking-off': CircleParkingOff,
  'circle-pause': CirclePause,
  'circle-percent': CirclePercent,
  'circle-play': CirclePlay,
  'circle-plus': CirclePlus,
  'circle-power': CirclePower,
  'circle-slash': CircleSlash,
  'circle-slash-2': CircleSlash2,
  'circle-stop': CircleStop,
  'circle-x': CircleX,
  'bot-message-square': BotMessageSquare,
  'flag-triangle-left': FlagTriangleLeft,
  'flag-triangle-right': FlagTriangleRight,
  hexagon: Hexagon,
  diamond: Diamond,
  'diamond-minus': DiamondMinus,
  'diamond-percent': DiamondPercent,
  'diamond-plus': DiamondPlus,
  lightbulb: Lightbulb,
  'lightbulb-off': LightbulbOff,
  flame: Flame,
  'flame-kindling': FlameKindling,
  bolt: Bolt,
  'earth-lock': EarthLock,
  'globe-lock': GlobeLock,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  'lock-keyhole-open': LockKeyholeOpen,
  'lock-open': LockOpen,
  flag: Flag,
  'flag-off': FlagOff,
  award: Award,
  crown: Crown,
  gem: Gem,
  badge: Badge,
  'badge-alert': BadgeAlert,
  'badge-cent': BadgeCent,
  'badge-check': BadgeCheck,
  'badge-dollar-sign': BadgeDollarSign,
  'badge-euro': BadgeEuro,
  'badge-help': BadgeHelp,
  'badge-indian-rupee': BadgeIndianRupee,
  'badge-info': BadgeInfo,
  'badge-japanese-yen': BadgeJapaneseYen,
  'badge-minus': BadgeMinus,
  'badge-percent': BadgePercent,
  'badge-plus': BadgePlus,
  'badge-pound-sterling': BadgePoundSterling,
  'badge-russian-ruble': BadgeRussianRuble,
  'badge-swiss-franc': BadgeSwissFranc,
  'badge-x': BadgeX,
  eye: Eye,
  'eye-closed': EyeClosed,
  'eye-off': EyeOff,
  bluetooth: Bluetooth,
  'bluetooth-connected': BluetoothConnected,
  'bluetooth-off': BluetoothOff,
  'bluetooth-searching': BluetoothSearching,
  battery: Battery,
  'battery-charging': BatteryCharging,
  'battery-full': BatteryFull,
  'battery-low': BatteryLow,
  'battery-medium': BatteryMedium,
  'battery-warning': BatteryWarning,
  atom: Atom,
  'flask-conical': FlaskConical,
  'flask-conical-off': FlaskConicalOff,
  'flask-round': FlaskRound,
  beaker: Beaker,
  dna: Dna,
  'dna-off': DnaOff,
  anchor: Anchor,
  castle: Castle,
  landmark: Landmark,
  church: Church,
  factory: Factory,
  coins: Coins,
  calculator: Calculator,
  gauge: Gauge,
  hourglass: Hourglass,
  'alarm-clock-minus': AlarmClockMinus,
  'alarm-clock-off': AlarmClockOff,
  'alarm-clock-plus': AlarmClockPlus,
  'alarm-smoke': AlarmSmoke,
  history: History,
  expand: Expand,
  'a-arrow-down': AArrowDown,
  'a-arrow-up': AArrowUp,
  'arrow-big-down': ArrowBigDown,
  'arrow-big-down-dash': ArrowBigDownDash,
  'arrow-big-left': ArrowBigLeft,
  'arrow-big-left-dash': ArrowBigLeftDash,
  'arrow-big-right': ArrowBigRight,
  'arrow-big-right-dash': ArrowBigRightDash,
  'arrow-big-up': ArrowBigUp,
  'arrow-big-up-dash': ArrowBigUpDash,
  'arrow-down': ArrowDown,
  'arrow-down-0-1': ArrowDown01,
  'arrow-down-1-0': ArrowDown10,
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-down-from-line': ArrowDownFromLine,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-narrow-wide': ArrowDownNarrowWide,
  'arrow-down-right': ArrowDownRight,
  'arrow-down-to-dot': ArrowDownToDot,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-down-up': ArrowDownUp,
  'arrow-down-wide-narrow': ArrowDownWideNarrow,
  'arrow-down-z-a': ArrowDownZA,
  'arrow-left': ArrowLeft,
  'arrow-left-from-line': ArrowLeftFromLine,
  'arrow-left-right': ArrowLeftRight,
  'arrow-left-to-line': ArrowLeftToLine,
  'arrow-right': ArrowRight,
  'arrow-right-from-line': ArrowRightFromLine,
  'arrow-right-left': ArrowRightLeft,
  'arrow-right-to-line': ArrowRightToLine,
  'arrow-up': ArrowUp,
  'arrow-up-0-1': ArrowUp01,
  'arrow-up-1-0': ArrowUp10,
  'arrow-up-a-z': ArrowUpAZ,
  'arrow-up-down': ArrowUpDown,
  'arrow-up-from-dot': ArrowUpFromDot,
  'arrow-up-from-line': ArrowUpFromLine,
  'arrow-up-left': ArrowUpLeft,
  'arrow-up-narrow-wide': ArrowUpNarrowWide,
  'arrow-up-right': ArrowUpRight,
  'arrow-up-to-line': ArrowUpToLine,
  'arrow-up-wide-narrow': ArrowUpWideNarrow,
  'arrow-up-z-a': ArrowUpZA,
  'clock-arrow-down': ClockArrowDown,
  'clock-arrow-up': ClockArrowUp,
  'git-pull-request-arrow': GitPullRequestArrow,
  'git-pull-request-create-arrow': GitPullRequestCreateArrow,
  'chevron-down': ChevronDown,
  'chevron-first': ChevronFirst,
  'chevron-last': ChevronLast,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
};
