import {
  Accessibility,
  Activity,
  Apple,
  Armchair,
  Baby,
  Banana,
  Bath,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  BeerOff,
  Bike,
  Bird,
  Bone,
  Brush,
  Bus,
  BusFront,
  CableCar,
  Cake,
  CakeSlice,
  Candy,
  CandyCane,
  CandyOff,
  Car,
  CarFront,
  CarTaxiFront,
  Carrot,
  Cat,
  CircleUser,
  CircleUserRound,
  Clover,
  Coffee,
  Contact,
  Cookie,
  Croissant,
  Cross,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dog,
  Donut,
  DoorClosed,
  DoorOpen,
  Dumbbell,
  Egg,
  EggFried,
  EggOff,
  Fence,
  Fish,
  FishOff,
  FishSymbol,
  Flower,
  Flower2,
  Footprints,
  Gamepad,
  Gamepad2,
  Gift,
  GlassWater,
  Glasses,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handshake,
  Headphones,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  HousePlug,
  HousePlus,
  Key,
  KeyRound,
  KeySquare,
  KeyboardMusic,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  Laugh,
  Leaf,
  ListMusic,
  ListTree,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
export const icons: Record<string, LucideIcon> = {
  'house-plug': HousePlug,
  'house-plus': HousePlus,
  bed: Bed,
  'bed-double': BedDouble,
  'bed-single': BedSingle,
  lamp: Lamp,
  'lamp-ceiling': LampCeiling,
  'lamp-desk': LampDesk,
  'lamp-floor': LampFloor,
  'lamp-wall-down': LampWallDown,
  'lamp-wall-up': LampWallUp,
  armchair: Armchair,
  'door-closed': DoorClosed,
  'door-open': DoorOpen,
  key: Key,
  'key-round': KeyRound,
  'key-square': KeySquare,
  bath: Bath,
  coffee: Coffee,
  cake: Cake,
  'cake-slice': CakeSlice,
  cookie: Cookie,
  apple: Apple,
  banana: Banana,
  carrot: Carrot,
  fish: Fish,
  'fish-off': FishOff,
  'fish-symbol': FishSymbol,
  beef: Beef,
  baby: Baby,
  cat: Cat,
  bird: Bird,
  'hand-heart': HandHeart,
  heart: Heart,
  'heart-crack': HeartCrack,
  'heart-handshake': HeartHandshake,
  'heart-off': HeartOff,
  'heart-pulse': HeartPulse,
  hand: Hand,
  'hand-coins': HandCoins,
  'hand-helping': HandHelping,
  'hand-metal': HandMetal,
  'hand-platter': HandPlatter,
  'circle-user': CircleUser,
  'circle-user-round': CircleUserRound,
  accessibility: Accessibility,
  laugh: Laugh,
  glasses: Glasses,
  dumbbell: Dumbbell,
  bike: Bike,
  'cable-car': CableCar,
  car: Car,
  'car-front': CarFront,
  'car-taxi-front': CarTaxiFront,
  bus: Bus,
  'bus-front': BusFront,
  'list-tree': ListTree,
  flower: Flower,
  'flower-2': Flower2,
  leaf: Leaf,
  gift: Gift,
  'keyboard-music': KeyboardMusic,
  'list-music': ListMusic,
  headphones: Headphones,
  gamepad: Gamepad,
  'gamepad-2': Gamepad2,
  'dice-1': Dice1,
  'dice-2': Dice2,
  'dice-3': Dice3,
  'dice-4': Dice4,
  'dice-5': Dice5,
  'dice-6': Dice6,
  brush: Brush,
  cross: Cross,
  activity: Activity,
  fence: Fence,
  egg: Egg,
  'egg-fried': EggFried,
  'egg-off': EggOff,
  croissant: Croissant,
  candy: Candy,
  'candy-cane': CandyCane,
  'candy-off': CandyOff,
  donut: Donut,
  beer: Beer,
  'beer-off': BeerOff,
  bone: Bone,
  handshake: Handshake,
  contact: Contact,
  footprints: Footprints,
  clover: Clover,
  'glass-water': GlassWater,
  dog: Dog,
};
