import {
  AlarmClock,
  Book,
  BookA,
  BookAudio,
  BookCheck,
  BookCopy,
  BookDashed,
  BookDown,
  BookHeadphones,
  BookHeart,
  BookImage,
  BookKey,
  BookLock,
  BookMarked,
  BookMinus,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookText,
  BookType,
  BookUp,
  BookUp2,
  BookUser,
  BookX,
  Bookmark,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkPlus,
  BookmarkX,
  BoomBox,
  Box,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseConveyorBelt,
  BriefcaseMedical,
  Bug,
  BugOff,
  BugPlay,
  Calendar,
  Calendar1,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarCog,
  CalendarDays,
  CalendarFold,
  CalendarHeart,
  CalendarMinus,
  CalendarMinus2,
  CalendarOff,
  CalendarPlus,
  CalendarPlus2,
  CalendarRange,
  CalendarSearch,
  CalendarSync,
  CalendarX,
  CalendarX2,
  ChartNetwork,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardMinus,
  ClipboardPaste,
  ClipboardPenLine,
  ClipboardPlus,
  ClipboardType,
  ClipboardX,
  Cloud,
  CloudAlert,
  CloudCog,
  CloudDownload,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  CloudUpload,
  Code,
  Database,
  DatabaseBackup,
  DatabaseZap,
  File,
  FileArchive,
  FileAudio,
  FileAudio2,
  FileBadge,
  FileBadge2,
  FileBox,
  FileChartLine,
  FileChartPie,
  FileCheck,
  FileCheck2,
  FileClock,
  FileCode,
  FileCode2,
  FileCog,
  FileDiff,
  FileDigit,
  FileDown,
  FileHeart,
  FileImage,
  FileInput,
  FileJson,
  FileJson2,
  FileKey,
  FileKey2,
  FileLock,
  FileLock2,
  FileMinus,
  FileMinus2,
  FileMusic,
  FileOutput,
  FilePenLine,
  FilePlus,
  FilePlus2,
  FileQuestion,
  FileScan,
  FileSearch,
  FileSearch2,
  FileSliders,
  FileSpreadsheet,
  FileStack,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileType2,
  FileUp,
  FileUser,
  FileVideo,
  FileVideo2,
  FileVolume,
  FileVolume2,
  FileWarning,
  FileX,
  FileX2,
  Folder,
  FolderArchive,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderCode,
  FolderCog,
  FolderDot,
  FolderDown,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOpenDot,
  FolderOutput,
  FolderPlus,
  FolderRoot,
  FolderSearch,
  FolderSearch2,
  FolderSymlink,
  FolderSync,
  FolderTree,
  FolderUp,
  FolderX,
  Hammer,
  Kanban,
  Library,
  Layers3,
  LibraryBig,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
export const icons: Record<string, LucideIcon> = {
  'layers-3': Layers3,
  briefcase: Briefcase,
  'briefcase-business': BriefcaseBusiness,
  'briefcase-conveyor-belt': BriefcaseConveyorBelt,
  'briefcase-medical': BriefcaseMedical,
  folder: Folder,
  'folder-archive': FolderArchive,
  'folder-check': FolderCheck,
  'folder-clock': FolderClock,
  'folder-closed': FolderClosed,
  'folder-code': FolderCode,
  'folder-cog': FolderCog,
  'folder-dot': FolderDot,
  'folder-down': FolderDown,
  'folder-git': FolderGit,
  'folder-git-2': FolderGit2,
  'folder-heart': FolderHeart,
  'folder-input': FolderInput,
  'folder-kanban': FolderKanban,
  'folder-key': FolderKey,
  'folder-lock': FolderLock,
  'folder-minus': FolderMinus,
  'folder-open': FolderOpen,
  'folder-open-dot': FolderOpenDot,
  'folder-output': FolderOutput,
  'folder-plus': FolderPlus,
  'folder-root': FolderRoot,
  'folder-search': FolderSearch,
  'folder-search-2': FolderSearch2,
  'folder-symlink': FolderSymlink,
  'folder-sync': FolderSync,
  'folder-tree': FolderTree,
  'folder-up': FolderUp,
  'folder-x': FolderX,
  file: File,
  'file-archive': FileArchive,
  'file-audio': FileAudio,
  'file-audio-2': FileAudio2,
  'file-badge': FileBadge,
  'file-badge-2': FileBadge2,
  'file-box': FileBox,
  'file-chart-line': FileChartLine,
  'file-chart-pie': FileChartPie,
  'file-check': FileCheck,
  'file-check-2': FileCheck2,
  'file-clock': FileClock,
  'file-code': FileCode,
  'file-code-2': FileCode2,
  'file-cog': FileCog,
  'file-diff': FileDiff,
  'file-digit': FileDigit,
  'file-down': FileDown,
  'file-heart': FileHeart,
  'file-image': FileImage,
  'file-input': FileInput,
  'file-json': FileJson,
  'file-json-2': FileJson2,
  'file-key': FileKey,
  'file-key-2': FileKey2,
  'file-lock': FileLock,
  'file-lock-2': FileLock2,
  'file-minus': FileMinus,
  'file-minus-2': FileMinus2,
  'file-music': FileMusic,
  'file-output': FileOutput,
  'file-pen-line': FilePenLine,
  'file-plus': FilePlus,
  'file-plus-2': FilePlus2,
  'file-question': FileQuestion,
  'file-scan': FileScan,
  'file-search': FileSearch,
  'file-search-2': FileSearch2,
  'file-sliders': FileSliders,
  'file-spreadsheet': FileSpreadsheet,
  'file-stack': FileStack,
  'file-symlink': FileSymlink,
  'file-terminal': FileTerminal,
  'file-text': FileText,
  'file-type': FileType,
  'file-type-2': FileType2,
  'file-up': FileUp,
  'file-user': FileUser,
  'file-video': FileVideo,
  'file-video-2': FileVideo2,
  'file-volume': FileVolume,
  'file-volume-2': FileVolume2,
  'file-warning': FileWarning,
  'file-x': FileX,
  'file-x-2': FileX2,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-copy': ClipboardCopy,
  'clipboard-list': ClipboardList,
  'clipboard-minus': ClipboardMinus,
  'clipboard-paste': ClipboardPaste,
  'clipboard-pen-line': ClipboardPenLine,
  'clipboard-plus': ClipboardPlus,
  'clipboard-type': ClipboardType,
  'clipboard-x': ClipboardX,
  book: Book,
  'book-a': BookA,
  'book-audio': BookAudio,
  'book-check': BookCheck,
  'book-copy': BookCopy,
  'book-dashed': BookDashed,
  'book-down': BookDown,
  'book-headphones': BookHeadphones,
  'book-heart': BookHeart,
  'book-image': BookImage,
  'book-key': BookKey,
  'book-lock': BookLock,
  'book-marked': BookMarked,
  'book-minus': BookMinus,
  'book-open': BookOpen,
  'book-open-check': BookOpenCheck,
  'book-open-text': BookOpenText,
  'book-plus': BookPlus,
  'book-text': BookText,
  'book-type': BookType,
  'book-up': BookUp,
  'book-up-2': BookUp2,
  'book-user': BookUser,
  'book-x': BookX,
  library: Library,
  'library-big': LibraryBig,
  kanban: Kanban,
  code: Code,
  database: Database,
  'database-backup': DatabaseBackup,
  'database-zap': DatabaseZap,
  cloud: Cloud,
  'cloud-alert': CloudAlert,
  'cloud-cog': CloudCog,
  'cloud-download': CloudDownload,
  'cloud-drizzle': CloudDrizzle,
  'cloud-fog': CloudFog,
  'cloud-hail': CloudHail,
  'cloud-lightning': CloudLightning,
  'cloud-moon': CloudMoon,
  'cloud-moon-rain': CloudMoonRain,
  'cloud-off': CloudOff,
  'cloud-rain': CloudRain,
  'cloud-rain-wind': CloudRainWind,
  'cloud-snow': CloudSnow,
  'cloud-sun': CloudSun,
  'cloud-sun-rain': CloudSunRain,
  'cloud-upload': CloudUpload,
  'chart-network': ChartNetwork,
  bug: Bug,
  'bug-off': BugOff,
  'bug-play': BugPlay,
  'boom-box': BoomBox,
  box: Box,
  bookmark: Bookmark,
  'bookmark-check': BookmarkCheck,
  'bookmark-minus': BookmarkMinus,
  'bookmark-plus': BookmarkPlus,
  'bookmark-x': BookmarkX,
  'calendar-search': CalendarSearch,
  hammer: Hammer,
  calendar: Calendar,
  'calendar-1': Calendar1,
  'calendar-arrow-down': CalendarArrowDown,
  'calendar-arrow-up': CalendarArrowUp,
  'calendar-check': CalendarCheck,
  'calendar-check-2': CalendarCheck2,
  'calendar-clock': CalendarClock,
  'calendar-cog': CalendarCog,
  'calendar-days': CalendarDays,
  'calendar-fold': CalendarFold,
  'calendar-heart': CalendarHeart,
  'calendar-minus': CalendarMinus,
  'calendar-minus-2': CalendarMinus2,
  'calendar-off': CalendarOff,
  'calendar-plus': CalendarPlus,
  'calendar-plus-2': CalendarPlus2,
  'calendar-range': CalendarRange,
  'calendar-sync': CalendarSync,
  'calendar-x': CalendarX,
  'calendar-x-2': CalendarX2,
  'alarm-clock': AlarmClock,
};
